### ISSUE TITLE
how to view the optimal exposure time at every point in time？

### ISSUE THREAD

**Issue by ouyangjiacs** [tedlasai/ae-video-platform#1]
Thank you very much for your great work. But there are some questions I would like to ask you.

Firstly, the interface of the code I downloaded does not match the one in the paper,

My requirement is to see the optimal exposure value for each time point in 40 exposure images, and how to view the optimal exposure time.

**Comment by tedlasai** [comment]
Hi, thank you for using our code. The third plot, should show the image selected by the autoexposure algorithm out of the 40 exposure images. You are right, that it is not optimal and instead the optimal frame with a smoothing. Meaning the optimal indices are computed and a smoothing is applied over the indices to prevent any jarring changes. We will provide an update to the interface to turn off smoothing so you can see the optimal exposure value without smoothing (I think this is what you want). We will aim to push this by Thursday night EST.

**Comment by tedlasai** [comment]
Please do let me know if I misunderstood.

**Comment by AliciaY-720** [comment]
Hi, @ouyangjiacs .  Thanks for your feedback. We just updated the code and the readme file. Users are allowed to input the number of frames for smoothness. Please input 1 if you would like to see the original outputs (without smoothness).

**Comment by ouyangjiacs** [comment]
> Hi, thank you for using our code. The third plot, should show the image selected by the autoexposure algorithm out of the 40 exposure images. You are right, that it is not optimal and instead the optimal frame with a smoothing. Meaning the optimal indices are computed and a smoothing is applied over the indices to prevent any jarring changes. We will provide an update to the interface to turn off smoothing so you can see the optimal exposure value without smoothing (I think this is what you want). We will aim to push this by Thursday night EST.

Your understanding is correct, thank you very much for your work, I will continue to learn from your work
![image](https://github.com/tedlasai/ae-video-platform/assets/115774907/1181e2e4-a6a3-4efe-8210-34d592df7fd4)

**Comment by ouyangjiacs** [comment]
> Hi, @ouyangjiacs . Thanks for your feedback. We just updated the code and the readme file. Users are allowed to input the number of frames for smoothness. Please input 1 if you would like to see the original outputs (without smoothness).
sincere thanks~
